# Generated by Django 4.2.2 on 2024-08-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='first_mailing_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время первой отправки рассылки'),
        ),
    ]
