# Generated by Django 4.2.2 on 2024-08-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_alter_mailing_first_mailing_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='mailattempt',
            options={'verbose_name': 'Попытка рассылки', 'verbose_name_plural': 'Попытки рассылки'},
        ),
        migrations.AlterModelOptions(
            name='mailing',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterField(
            model_name='mailing',
            name='period',
            field=models.IntegerField(choices=[(1, 'once a minute'), (5, 'once in five minutes'), (60, 'once an hour'), (1440, 'once a day')], default=1, verbose_name='Периодичность отправки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.IntegerField(choices=[(1, 'Created'), (2, 'Working...'), (3, 'Completed')], default=1, verbose_name='Статус рассылки'),
        ),
    ]
