# Generated by Django 4.2.2 on 2024-08-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_alter_client_options_alter_mailattempt_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='next_mailing_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время следующей отправки рассылки'),
        ),
    ]
