# Generated by Django 4.2.2 on 2024-09-01 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0006_alter_mailing_options_mailing_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_view_mailing_detail', 'Can view mailing details'), ('set_active', 'Can activate/deactivate mailing')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
